### ISSUE TITLE
Alterações no diagrama de classes

### ISSUE THREAD

**Issue by danyelliasmanso** [DLL-S/ueg-construcao-software#24]
- No método listarProdutos(), retorna uma lista de produtos.
- Incluir os métodos, deletar e listar nas classes Marca e Categoria.

**Comment by lucasdemoraesc** [comment]
Outras possíveis alterações:
- Remover dados de usuário, da classe funcionário
- Analisar inativação/deleção de funcionários, clientes e produtos

**Comment by lucasdemoraesc** [comment]
Entidade usuário: (Remover senha de acesso de Funcionário)

Criar entidade Usuário
- email
- senha
- tipoUsuário
