### ISSUE TITLE
Viabilidade do método de deleção

### ISSUE THREAD

**Issue by danyelliasmanso** [DLL-S/ueg-construcao-software#30]
Precisamos discutir a viabilidade do método de deleção. Provavelmente o método deletar deverá ser substituído por inativar.

_Originally posted by @lucasdemoraesc in https://github.com/DLL-S/ueg-construcao-software/pull/29#r563716456_

**Comment by lucasdemoraesc** [comment]
Inativar

Adequar todas as entidades
