### ISSUE TITLE
Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by lucasdemoraesc** [DLL-S/ueg-construcao-software#8]
### Atividades:
- [ ] **Baixar e instalar o git:** https://git-scm.com/downloads

- [ ] **Baixar e Instalar o Java 11:** https://jdk.java.net/java-se-ri/11

- [ ] **Baixar o Spring tools:** https://spring.io/tools

- [ ] **Baixar e Instalar o PostgreSQL versão 9.6:** https://www.enterprisedb.com/downloads/postgres-postgresql-downloads

- [ ] **Baixar e Instalar o DBeaver (Apenas 64 bits, utilizar pgAdmin para 32 bits):** https://dbeaver.io/download/

- [ ] **Conectar o DBeaver ao PostgreSQL**

- [ ] **Baixar e Instalar o Visual Studio Code:** https://code.visualstudio.com/

- [ ] **Baixar e Instalar o NodeJs:** https://nodejs.org/dist/v12.18.3/

- [ ] **Instalar o Angular:** `npm install -g @angular/cli`

- [ ] **Baixar e instalar o Postman:** https://www.postman.com/downloads/

**Comment by lucasdemoraesc** [comment]
### Atividades:
- [ ] **Baixar e Instalar o Java:** https://jdk.java.net/java-se-ri/11

- [ ] **Baixar o Spring tools:** https://spring.io/tools

- [ ] **Baixar e Instalar o PostgreSQL versão 9.6:** https://www.enterprisedb.com/downloads/postgres-postgresql-downloads

- [ ] **Baixar e Instalar o DBeaver (Apenas 64 bits, utilizar pgAdmin para 32 bits):** https://dbeaver.io/download/

- [ ] **Conectar o DBeaver ao PostgreSQL**

- [ ] **Baixar e Instalar o Visual Studio Code:** https://code.visualstudio.com/

- [ ] **Baixar e Instalar o NodeJs:** https://nodejs.org/dist/v12.18.3/

- [ ] **Instalar o Angular:** `npm install -g @angular/cli`

- [ ] **Baixar e instalar o Postman:** https://www.postman.com/downloads/

**Comment by danyelliasmanso** [comment]
Instalação das ferramentas concluídas.
